version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: sectors
      POSTGRES_PASSWORD: sectors
      POSTGRES_DB: helmes
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
